export const planets = [
  {
    id: '1',
    animation: require('../assets/p1.json'),
    universe: 'Harvard',
    metaData: {
      fullName: 'Harvard University',
      location: 'Massachusetts, USA',
      rank: 3,
      activeUsers: 1200000,
      travleFare: 120,
    },
  },
  {
    id: '2',
    animation: require('../assets/p2.json'),
    universe: 'MIT',
    metaData: {
      fullName: 'Massachusetts Institute of Technology',
      location: 'Massachusetts, USA',
      rank: 1,
      activeUsers: 950000,
      travleFare: 130,
    },
  },
  {
    id: '3',
    animation: require('../assets/p3.json'),
    universe: 'Oxford',
    metaData: {
      fullName: 'University of Oxford',
      location: 'Oxford, England',
      rank: 4,
      activeUsers: 890000,
      travleFare: 150,
    },
  },
  {
    id: '4',
    animation: require('../assets/p4.json'),
    universe: 'Cambridge',
    metaData: {
      fullName: 'University of Cambridge',
      location: 'Cambridge, England',
      rank: 5,
      activeUsers: 870000,
      travleFare: 140,
    },
  },
  {
    id: '5',
    animation: require('../assets/p5.json'),
    universe: 'Stanford',
    metaData: {
      fullName: 'Stanford University',
      location: 'California, USA',
      rank: 2,
      activeUsers: 1100000,
      travleFare: 125,
    },
  },
  {
    id: '6',
    animation: require('../assets/p6.json'),
    universe: 'IIT-Delhi',
    metaData: {
      fullName: 'Indian Institute of Technology Delhi',
      location: 'Delhi, India',
      rank: 7,
      activeUsers: 600000,
      travleFare: 50,
    },
  },
  {
    id: '7',
    animation: require('../assets/p7.json'),
    universe: 'LPU',
    metaData: {
      fullName: 'Lovely Professional University',
      location: 'Punjab, India',
      rank: 25,
      activeUsers: 800000,
      travleFare: 30,
    },
  },
  {
    id: '8',
    animation: require('../assets/p8.json'),
    universe: 'Cambridge',
    metaData: {
      fullName: 'University of Cambridge (Branch)',
      location: 'Cambridge, England',
      rank: 5,
      activeUsers: 860000,
      travleFare: 140,
    },
  },
  {
    id: '9',
    animation: require('../assets/p9.json'),
    universe: 'IISc',
    metaData: {
      fullName: 'Indian Institute of Science',
      location: 'Bangalore, India',
      rank: 6,
      activeUsers: 500000,
      travleFare: 55,
    },
  },
  {
    id: '10',
    animation: require('../assets/p10.json'),
    universe: 'IIM-A',
    metaData: {
      fullName: 'Indian Institute of Management Ahmedabad',
      location: 'Gujarat, India',
      rank: 8,
      activeUsers: 400000,
      travleFare: 60,
    },
  },
];
